### ISSUE TITLE
Documentation: getting up and running

### ISSUE THREAD

**Issue by tharna** [wunderkraut/radi-project-wundertoolswrapper#28] opened 2017-02-10 12:13 UTC
Readme should have clear steps how to get up and running after build.
e.g. How to bring the instances up (radi up)
How to access your site (go to localhost: [xx]81, where xx is the value you gave as prefix)

**Comment by james-nesbitt** [comment] 2017-02-10 12:46
probably a duplicate of https://github.com/wunderkraut/radi-project-wundertoolswrapper/issues/24

**Closed as completed** 2017-02-10 12:46 UTC
Labels: invalid
